---
AWSTemplateFormatVersion: 2010-09-09
Description: Component 2
Parameters:
  SsmParamName:
    Type: String
    Default: default-param

Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref SsmParamName
      Type: String
      Value: date
      Description: SSM Parameter for running date command.
      AllowedPattern: "^[a-zA-Z]{1,10}$"
      Tags:
        Environment: DEV
        Team: blue