---
AWSTemplateFormatVersion: 2010-09-09
Description: Component 1 Spoke
Parameters:
  SsmParamName:
    Type: String
    Default: spoke-param-alt

Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref SsmParamName
      Type: String
      Value: 'testing123456'
      Description: SSM Parameter.
      Tags:
        Environment: DEV