---
AWSTemplateFormatVersion: 2010-09-09
Description: Component 1 Hub
Parameters:
  SsmParamName:
    Type: String
    Default: default-param-alt

Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref SsmParamName
      Type: String
      Value: 'testing789'
      # BadProp: ForceCfnLintError # Uncomment to demonstrate cfn-lint failure
      Description: SSM Parameter.
      Tags:
        Environment: DEV