---
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ArtifactsBucket:
    Description: Name of the S3 bucket where cicd artifacts are stored.
    Type: String
  GitHubOrg:
    Description: Name of the GitHub Organization.
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String
  RepositoryName:
    Description: Name of the GitHub Repository.
    Type: String

Conditions:
  CreateOIDCProvider: !Equals 
    - !Ref OIDCProviderArn
    - ""

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If 
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*
      Description: !Sub Role used by GitHub Actions in repo ${GitHubOrg}/${RepositoryName}
      ManagedPolicyArns:
        - !Ref Policy
      Tags: 
        - Key: Environment
          Value: DEV

  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:*'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:GetObjec*'
              - 's3:ListBucket'
              - 's3:PutObjec*'
            Resource:
              - !Sub 'arn:aws:s3:::${ArtifactsBucket}'
              - !Sub 'arn:aws:s3:::${ArtifactsBucket}/*'
          - Effect: Allow
            Action:
              - 'ssm:*Param*'
              - 'ssm:*Tag*'
            Resource: '*'
      ManagedPolicyName: cicd-policy


  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1

Outputs:
  Role:
    Value: !GetAtt Role.Arn