name: CD-ALL

on:
  # This would trigger FULL deployment of all components on pushes to the main branch
  # push:
  #   branches: [ main ]

  # This would trigger deployment (CD) upon completion of CI
  # workflow_run:
  #   workflows:
  #     - "CI-ALL"
  #   branches:
  #     - "*"
  #   types:
  #     - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-component1-hub:
    uses: ./.github/workflows/deploy-cfn.yml
    with:
      aws-region: us-east-2
      base-path: './src/infra'
      config-file: 'stack-config.yml'
      deployment-type: stack
      name: component1-hub
    secrets:
      gh-artifacts-bucket: ${{ secrets.GH_ACTIONS_BUCKET }}
      gh-iam-role: ${{ secrets.GH_IAM_ROLE }}
  deploy-component1-spoke:
    needs: [deploy-component1-hub]
    uses: ./.github/workflows/deploy-cfn.yml
    with:
      aws-region: us-east-2
      base-path: './src/infra'
      config-file: 'stackset-config.yml'
      deployment-type: stackset
      name: component1-spoke
    secrets:
      gh-artifacts-bucket: ${{ secrets.GH_ACTIONS_BUCKET }}
      gh-iam-role: ${{ secrets.GH_IAM_ROLE }}
  deploy-component2:
    uses: ./.github/workflows/deploy-cfn.yml
    with:
      aws-region: us-east-2
      base-path: './src/infra'
      config-file: 'stack-config.yml'
      deployment-type: stack
      name: component2
    secrets:
      gh-artifacts-bucket: ${{ secrets.GH_ACTIONS_BUCKET }}
      gh-iam-role: ${{ secrets.GH_IAM_ROLE }}
