name: CD component2

on:
  # Deploy on push/merge to main
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'src/infra/component2/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-component:
    uses: ./.github/workflows/deploy-cfn.yml
    with:
      aws-region: us-east-2
      base-path: './src/infra'
      config-file: 'stack-config.yml'
      deployment-type: stack
      name: component2
    secrets:
      gh-artifacts-bucket: ${{ secrets.GH_ACTIONS_BUCKET }}
      gh-iam-role: ${{ secrets.GH_IAM_ROLE }}
