name: CI component2

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'src/infra/component2/**'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'src/infra/component2/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  qa-checks:
    uses: ./.github/workflows/qa-cfn.yml
    with:
      aws-region: us-east-2
      base-path: './src/infra'
      name: 'component2'
    secrets:
      gh-iam-role: ${{ secrets.GH_IAM_ROLE }}

